import {
  FileText,
  Terminal,
  Image,
  Database,
  Package,
  Pencil,
  Braces,
  type LucideIcon,
} from 'lucide-react'
import {
  SiTypescript,
  SiJavascript,
  SiReact,
  SiPython,
  SiRust,
  SiGo,
  SiKotlin,
  SiSwift,
  SiRuby,
  SiPhp,
  SiHaskell,
  SiElixir,
  SiScala,
  SiNodedotjs,
  SiJson,
  SiHtml5,
  SiCss,
  SiSass,
  SiMarkdown,
  SiDocker,
  SiGit,
  SiNpm,
  SiWebpack,
  SiVite,
  SiBabel,
  SiEslint,
  SiPrettier,
  SiJest,
  SiMocha,
  SiCypress,
  SiMongodb,
  SiPostgresql,
  SiMysql,
  SiSqlite,
  SiRedis,
  SiNginx,
  SiApache,
  SiLinux,
  SiUbuntu,
  SiApple,
  SiSublimetext,
  SiVim,
  SiNeovim,
  SiObsidian,
  SiNotion,
  SiFigma,
  SiBlender,
  SiUnrealengine,
  SiUnity,
  SiGodotengine,
  SiCplusplus,
  SiC,
  SiSpring,
  SiYaml,
  SiXml,
  SiVuedotjs,
  SiSvelte,
  SiAngular,
  SiExpress,
  SiNestjs,
  SiFastify,
  SiSvg,
} from 'react-icons/si'
import { MdFolder, MdFolderOpen } from 'react-icons/md'
import type { IconThemeDefinition } from './types'

const fileIconMap: Record<string, LucideIcon> = {
  html: SiHtml5 as unknown as LucideIcon,
  htm: SiHtml5 as unknown as LucideIcon,
  css: SiCss as unknown as LucideIcon,
  scss: SiSass as unknown as LucideIcon,
  less: SiSass as unknown as LucideIcon,
  js: SiJavascript as unknown as LucideIcon,
  jsx: SiReact as unknown as LucideIcon,
  ts: SiTypescript as unknown as LucideIcon,
  tsx: SiReact as unknown as LucideIcon,
  json: SiJson as unknown as LucideIcon,
  md: SiMarkdown as unknown as LucideIcon,
  markdown: SiMarkdown as unknown as LucideIcon,
  txt: FileText,
  py: SiPython as unknown as LucideIcon,
  rs: SiRust as unknown as LucideIcon,
  go: SiGo as unknown as LucideIcon,
  java: SiSpring as unknown as LucideIcon,
  cpp: SiCplusplus as unknown as LucideIcon,
  c: SiC as unknown as LucideIcon,
  h: SiC as unknown as LucideIcon,
  hpp: SiCplusplus as unknown as LucideIcon,
  rb: SiRuby as unknown as LucideIcon,
  swift: SiSwift as unknown as LucideIcon,
  kt: SiKotlin as unknown as LucideIcon,
  kts: SiKotlin as unknown as LucideIcon,
  php: SiPhp as unknown as LucideIcon,
  hs: SiHaskell as unknown as LucideIcon,
  ex: SiElixir as unknown as LucideIcon,
  exs: SiElixir as unknown as LucideIcon,
  scala: SiScala as unknown as LucideIcon,
  sql: SiSqlite as unknown as LucideIcon,
  sh: Terminal,
  bash: Terminal,
  zsh: Terminal,
  yaml: SiYaml as unknown as LucideIcon,
  yml: SiYaml as unknown as LucideIcon,
  xml: SiXml as unknown as LucideIcon,
  dockerfile: SiDocker as unknown as LucideIcon,
  dockerignore: SiDocker as unknown as LucideIcon,
  gitignore: SiGit as unknown as LucideIcon,
  node: SiNodedotjs as unknown as LucideIcon,
  package: SiNpm as unknown as LucideIcon,
  lock: SiNpm as unknown as LucideIcon,
  webpack: SiWebpack as unknown as LucideIcon,
  vite: SiVite as unknown as LucideIcon,
  babel: SiBabel as unknown as LucideIcon,
  eslint: SiEslint as unknown as LucideIcon,
  prettier: SiPrettier as unknown as LucideIcon,
  jest: SiJest as unknown as LucideIcon,
  mocha: SiMocha as unknown as LucideIcon,
  cypress: SiCypress as unknown as LucideIcon,
  vue: SiVuedotjs as unknown as LucideIcon,
  svelte: SiSvelte as unknown as LucideIcon,
  angular: SiAngular as unknown as LucideIcon,
  express: SiExpress as unknown as LucideIcon,
  nest: SiNestjs as unknown as LucideIcon,
  fastify: SiFastify as unknown as LucideIcon,
  mongodb: SiMongodb as unknown as LucideIcon,
  postgresql: SiPostgresql as unknown as LucideIcon,
  mysql: SiMysql as unknown as LucideIcon,
  sqlite: SiSqlite as unknown as LucideIcon,
  redis: SiRedis as unknown as LucideIcon,
  nginx: SiNginx as unknown as LucideIcon,
  apache: SiApache as unknown as LucideIcon,
  linux: SiLinux as unknown as LucideIcon,
  ubuntu: SiUbuntu as unknown as LucideIcon,
  apple: SiApple as unknown as LucideIcon,
  windows: Braces,
  vscode: Braces,
  sublime: SiSublimetext as unknown as LucideIcon,
  vim: SiVim as unknown as LucideIcon,
  neovim: SiNeovim as unknown as LucideIcon,
  obsidian: SiObsidian as unknown as LucideIcon,
  notion: SiNotion as unknown as LucideIcon,
  figma: SiFigma as unknown as LucideIcon,
  photoshop: Pencil,
  illustrator: Pencil,
  premiere: Pencil,
  blender: SiBlender as unknown as LucideIcon,
  unreal: SiUnrealengine as unknown as LucideIcon,
  unity: SiUnity as unknown as LucideIcon,
  godot: SiGodotengine as unknown as LucideIcon,
  svg: SiSvg as unknown as LucideIcon,
  png: Image,
  jpg: Image,
  jpeg: Image,
  gif: Image,
  webp: Image,
  ico: Image,
  pdf: FileText,
  doc: FileText,
  docx: FileText,
  xls: Database,
  xlsx: Database,
  zip: Package,
  tar: Package,
  gz: Package,
  rar: Package,
  default: FileText,
}

const fileIconColors: Record<string, string> = {
  html: 'text-peach',
  htm: 'text-peach',
  css: 'text-blue',
  scss: 'text-pink',
  less: 'text-indigo',
  js: 'text-yellow',
  jsx: 'text-teal',
  ts: 'text-sapphire',
  tsx: 'text-blue',
  json: 'text-green',
  md: 'text-overlay2',
  markdown: 'text-overlay2',
  txt: 'text-overlay1',
  py: 'text-sky',
  rs: 'text-peach',
  go: 'text-teal',
  java: 'text-red',
  cpp: 'text-blue',
  c: 'text-blue',
  h: 'text-mauve',
  hpp: 'text-mauve',
  rb: 'text-red',
  swift: 'text-peach',
  kt: 'text-purple',
  kts: 'text-purple',
  php: 'text-indigo',
  hs: 'text-purple',
  ex: 'text-mauve',
  exs: 'text-mauve',
  scala: 'text-red',
  sql: 'text-yellow',
  sh: 'text-green',
  bash: 'text-green',
  zsh: 'text-green',
  yaml: 'text-red',
  yml: 'text-red',
  xml: 'text-peach',
  dockerfile: 'text-blue',
  dockerignore: 'text-blue',
  gitignore: 'text-peach',
  node: 'text-green',
  package: 'text-red',
  lock: 'text-red',
  webpack: 'text-blue',
  vite: 'text-purple',
  babel: 'text-yellow',
  eslint: 'text-purple',
  prettier: 'text-pink',
  jest: 'text-red',
  mocha: 'text-red',
  cypress: 'text-green',
  vue: 'text-green',
  svelte: 'text-peach',
  angular: 'text-red',
  express: 'text-overlay1',
  nest: 'text-red',
  fastify: 'text-green',
  mongodb: 'text-green',
  postgresql: 'text-blue',
  mysql: 'text-blue',
  sqlite: 'text-blue',
  redis: 'text-red',
  nginx: 'text-green',
  apache: 'text-red',
  linux: 'text-yellow',
  ubuntu: 'text-peach',
  apple: 'text-overlay1',
  windows: 'text-blue',
  vscode: 'text-blue',
  sublime: 'text-peach',
  vim: 'text-green',
  neovim: 'text-green',
  obsidian: 'text-purple',
  notion: 'text-overlay1',
  figma: 'text-pink',
  photoshop: 'text-blue',
  illustrator: 'text-peach',
  premiere: 'text-purple',
  blender: 'text-peach',
  unreal: 'text-blue',
  unity: 'text-overlay1',
  godot: 'text-blue',
  svg: 'text-yellow',
  png: 'text-pink',
  jpg: 'text-pink',
  jpeg: 'text-pink',
  gif: 'text-purple',
  webp: 'text-indigo',
  ico: 'text-blue',
  pdf: 'text-red',
  doc: 'text-blue',
  docx: 'text-blue',
  xls: 'text-green',
  xlsx: 'text-green',
  zip: 'text-yellow',
  tar: 'text-yellow',
  gz: 'text-yellow',
  rar: 'text-purple',
  default: 'text-overlay2',
}

export const catppuccinIconsTheme: IconThemeDefinition = {
  id: 'catppuccin-icons',
  name: 'Catppuccin Icons',
  description: 'Soft pastel candy-colored file icons',
  fileIconMap,
  fileIconColors,
  folderIcon: MdFolder as unknown as LucideIcon,
  folderOpenIcon: MdFolderOpen as unknown as LucideIcon,
  defaultIcon: FileText,
  defaultColor: 'text-overlay2',
  folderColor: 'text-yellow',
}