import {
  FileText,
  FileCode,
  FileJson,
  FileImage,
  FileSpreadsheet,
  FileArchive,
  FileTerminal,
  File,
  Folder,
  FolderOpen,
  Terminal,
  Image,
  Database,
  Package,
  Braces,
  Code,
  Globe,
  Book,
  Cpu,
  HardDrive,
  type LucideIcon,
} from 'lucide-react'
import type { IconThemeDefinition } from './types'

const fileIconMap: Record<string, LucideIcon> = {
  html: Globe,
  htm: Globe,
  css: Code,
  scss: Code,
  less: Code,
  js: FileCode,
  jsx: FileCode,
  ts: FileCode,
  tsx: FileCode,
  json: FileJson,
  md: Book,
  markdown: Book,
  txt: FileText,
  py: FileCode,
  rs: FileCode,
  go: FileCode,
  java: FileCode,
  cpp: FileCode,
  c: FileCode,
  h: FileCode,
  hpp: FileCode,
  rb: FileCode,
  swift: FileCode,
  kt: FileCode,
  kts: FileCode,
  php: FileCode,
  hs: FileCode,
  ex: FileCode,
  exs: FileCode,
  scala: FileCode,
  sql: Database,
  sh: Terminal,
  bash: Terminal,
  zsh: Terminal,
  yaml: FileCode,
  yml: FileCode,
  xml: FileCode,
  dockerfile: Cpu,
  dockerignore: Cpu,
  gitignore: FileCode,
  node: Cpu,
  package: Package,
  lock: FileCode,
  webpack: HardDrive,
  vite: HardDrive,
  babel: HardDrive,
  eslint: HardDrive,
  prettier: HardDrive,
  jest: FileCode,
  mocha: FileCode,
  cypress: FileCode,
  vue: FileCode,
  svelte: FileCode,
  angular: FileCode,
  express: Cpu,
  nest: Cpu,
  fastify: Cpu,
  mongodb: Database,
  postgresql: Database,
  mysql: Database,
  sqlite: Database,
  redis: Database,
  nginx: Cpu,
  apache: Cpu,
  linux: Terminal,
  ubuntu: Terminal,
  apple: Terminal,
  windows: Terminal,
  vscode: Code,
  sublime: File,
  vim: Terminal,
  neovim: Terminal,
  obsidian: Book,
  notion: FileText,
  figma: FileImage,
  photoshop: FileImage,
  illustrator: FileImage,
  premiere: FileImage,
  blender: FileImage,
  unreal: FileCode,
  unity: FileCode,
  godot: FileCode,
  svg: FileImage,
  png: FileImage,
  jpg: FileImage,
  jpeg: FileImage,
  gif: FileImage,
  webp: FileImage,
  ico: FileImage,
  pdf: FileText,
  doc: FileText,
  docx: FileText,
  xls: FileSpreadsheet,
  xlsx: FileSpreadsheet,
  zip: FileArchive,
  tar: FileArchive,
  gz: FileArchive,
  rar: FileArchive,
  default: FileText,
}

const fileIconColors: Record<string, string> = {
  html: 'text-orange-500',
  htm: 'text-orange-500',
  css: 'text-blue-500',
  scss: 'text-pink-500',
  less: 'text-indigo-500',
  js: 'text-yellow-500',
  jsx: 'text-cyan-500',
  ts: 'text-blue-600',
  tsx: 'text-blue-500',
  json: 'text-emerald-500',
  md: 'text-slate-500',
  markdown: 'text-slate-500',
  txt: 'text-gray-500',
  py: 'text-sky-500',
  rs: 'text-orange-600',
  go: 'text-cyan-500',
  java: 'text-red-500',
  cpp: 'text-blue-700',
  c: 'text-blue-600',
  h: 'text-violet-500',
  hpp: 'text-violet-600',
  rb: 'text-red-600',
  swift: 'text-orange-500',
  kt: 'text-purple-500',
  kts: 'text-purple-500',
  php: 'text-indigo-500',
  hs: 'text-purple-600',
  ex: 'text-violet-500',
  exs: 'text-violet-500',
  scala: 'text-red-500',
  sql: 'text-amber-600',
  sh: 'text-green-600',
  bash: 'text-green-600',
  zsh: 'text-green-500',
  yaml: 'text-red-400',
  yml: 'text-red-400',
  xml: 'text-orange-400',
  dockerfile: 'text-blue-500',
  dockerignore: 'text-blue-500',
  gitignore: 'text-orange-500',
  node: 'text-green-500',
  package: 'text-red-500',
  lock: 'text-red-500',
  webpack: 'text-blue-500',
  vite: 'text-purple-500',
  babel: 'text-yellow-500',
  eslint: 'text-purple-500',
  prettier: 'text-pink-500',
  jest: 'text-red-500',
  mocha: 'text-red-500',
  cypress: 'text-green-500',
  vue: 'text-green-500',
  svelte: 'text-orange-500',
  angular: 'text-red-500',
  express: 'text-gray-500',
  nest: 'text-red-500',
  fastify: 'text-green-500',
  mongodb: 'text-green-500',
  postgresql: 'text-blue-500',
  mysql: 'text-blue-600',
  sqlite: 'text-blue-500',
  redis: 'text-red-500',
  nginx: 'text-green-500',
  apache: 'text-red-500',
  linux: 'text-yellow-500',
  ubuntu: 'text-orange-500',
  apple: 'text-gray-500',
  windows: 'text-blue-500',
  vscode: 'text-blue-500',
  sublime: 'text-orange-500',
  vim: 'text-green-500',
  neovim: 'text-green-500',
  obsidian: 'text-purple-500',
  notion: 'text-gray-500',
  figma: 'text-pink-500',
  photoshop: 'text-blue-600',
  illustrator: 'text-orange-500',
  premiere: 'text-purple-500',
  blender: 'text-orange-500',
  unreal: 'text-blue-500',
  unity: 'text-gray-500',
  godot: 'text-blue-500',
  svg: 'text-amber-500',
  png: 'text-pink-500',
  jpg: 'text-pink-500',
  jpeg: 'text-pink-500',
  gif: 'text-purple-500',
  webp: 'text-indigo-500',
  ico: 'text-blue-400',
  pdf: 'text-red-500',
  doc: 'text-blue-600',
  docx: 'text-blue-600',
  xls: 'text-green-600',
  xlsx: 'text-green-600',
  zip: 'text-amber-600',
  tar: 'text-amber-600',
  gz: 'text-amber-500',
  rar: 'text-purple-600',
  default: 'text-slate-500',
}

export const classicTheme: IconThemeDefinition = {
  id: 'classic',
  name: 'Classic',
  description: 'Simple Lucide icons, no external dependencies',
  fileIconMap,
  fileIconColors,
  folderIcon: Folder,
  folderOpenIcon: FolderOpen,
  defaultIcon: FileText,
  defaultColor: 'text-slate-500',
  folderColor: 'text-amber-500',
}
