import {
  FileText,
  Terminal,
  Image,
  Database,
  Package,
  Pencil,
  Braces,
  type LucideIcon,
} from 'lucide-react'
import {
  SiTypescript,
  SiJavascript,
  SiReact,
  SiPython,
  SiRust,
  SiGo,
  SiKotlin,
  SiSwift,
  SiRuby,
  SiPhp,
  SiHaskell,
  SiElixir,
  SiScala,
  SiNodedotjs,
  SiJson,
  SiHtml5,
  SiCss,
  SiSass,
  SiMarkdown,
  SiDocker,
  SiGit,
  SiNpm,
  SiWebpack,
  SiVite,
  SiBabel,
  SiEslint,
  SiPrettier,
  SiJest,
  SiMocha,
  SiCypress,
  SiMongodb,
  SiPostgresql,
  SiMysql,
  SiSqlite,
  SiRedis,
  SiNginx,
  SiApache,
  SiLinux,
  SiUbuntu,
  SiApple,
  SiSublimetext,
  SiVim,
  SiNeovim,
  SiObsidian,
  SiNotion,
  SiFigma,
  SiBlender,
  SiUnrealengine,
  SiUnity,
  SiGodotengine,
  SiCplusplus,
  SiC,
  SiSpring,
  SiYaml,
  SiXml,
  SiVuedotjs,
  SiSvelte,
  SiAngular,
  SiExpress,
  SiNestjs,
  SiFastify,
  SiSvg,
} from 'react-icons/si'
import { MdFolder, MdFolderOpen } from 'react-icons/md'
import type { IconThemeDefinition } from './types'

const fileIconMap: Record<string, LucideIcon> = {
  html: SiHtml5 as unknown as LucideIcon,
  htm: SiHtml5 as unknown as LucideIcon,
  css: SiCss as unknown as LucideIcon,
  scss: SiSass as unknown as LucideIcon,
  less: SiSass as unknown as LucideIcon,
  js: SiJavascript as unknown as LucideIcon,
  jsx: SiReact as unknown as LucideIcon,
  ts: SiTypescript as unknown as LucideIcon,
  tsx: SiReact as unknown as LucideIcon,
  json: SiJson as unknown as LucideIcon,
  md: SiMarkdown as unknown as LucideIcon,
  markdown: SiMarkdown as unknown as LucideIcon,
  txt: FileText,
  py: SiPython as unknown as LucideIcon,
  rs: SiRust as unknown as LucideIcon,
  go: SiGo as unknown as LucideIcon,
  java: SiSpring as unknown as LucideIcon,
  cpp: SiCplusplus as unknown as LucideIcon,
  c: SiC as unknown as LucideIcon,
  h: SiC as unknown as LucideIcon,
  hpp: SiCplusplus as unknown as LucideIcon,
  rb: SiRuby as unknown as LucideIcon,
  swift: SiSwift as unknown as LucideIcon,
  kt: SiKotlin as unknown as LucideIcon,
  kts: SiKotlin as unknown as LucideIcon,
  php: SiPhp as unknown as LucideIcon,
  hs: SiHaskell as unknown as LucideIcon,
  ex: SiElixir as unknown as LucideIcon,
  exs: SiElixir as unknown as LucideIcon,
  scala: SiScala as unknown as LucideIcon,
  sql: SiSqlite as unknown as LucideIcon,
  sh: Terminal,
  bash: Terminal,
  zsh: Terminal,
  yaml: SiYaml as unknown as LucideIcon,
  yml: SiYaml as unknown as LucideIcon,
  xml: SiXml as unknown as LucideIcon,
  dockerfile: SiDocker as unknown as LucideIcon,
  dockerignore: SiDocker as unknown as LucideIcon,
  gitignore: SiGit as unknown as LucideIcon,
  node: SiNodedotjs as unknown as LucideIcon,
  package: SiNpm as unknown as LucideIcon,
  lock: SiNpm as unknown as LucideIcon,
  webpack: SiWebpack as unknown as LucideIcon,
  vite: SiVite as unknown as LucideIcon,
  babel: SiBabel as unknown as LucideIcon,
  eslint: SiEslint as unknown as LucideIcon,
  prettier: SiPrettier as unknown as LucideIcon,
  jest: SiJest as unknown as LucideIcon,
  mocha: SiMocha as unknown as LucideIcon,
  cypress: SiCypress as unknown as LucideIcon,
  vue: SiVuedotjs as unknown as LucideIcon,
  svelte: SiSvelte as unknown as LucideIcon,
  angular: SiAngular as unknown as LucideIcon,
  express: SiExpress as unknown as LucideIcon,
  nest: SiNestjs as unknown as LucideIcon,
  fastify: SiFastify as unknown as LucideIcon,
  mongodb: SiMongodb as unknown as LucideIcon,
  postgresql: SiPostgresql as unknown as LucideIcon,
  mysql: SiMysql as unknown as LucideIcon,
  sqlite: SiSqlite as unknown as LucideIcon,
  redis: SiRedis as unknown as LucideIcon,
  nginx: SiNginx as unknown as LucideIcon,
  apache: SiApache as unknown as LucideIcon,
  linux: SiLinux as unknown as LucideIcon,
  ubuntu: SiUbuntu as unknown as LucideIcon,
  apple: SiApple as unknown as LucideIcon,
  windows: Braces,
  vscode: Braces,
  sublime: SiSublimetext as unknown as LucideIcon,
  vim: SiVim as unknown as LucideIcon,
  neovim: SiNeovim as unknown as LucideIcon,
  obsidian: SiObsidian as unknown as LucideIcon,
  notion: SiNotion as unknown as LucideIcon,
  figma: SiFigma as unknown as LucideIcon,
  photoshop: Pencil,
  illustrator: Pencil,
  premiere: Pencil,
  blender: SiBlender as unknown as LucideIcon,
  unreal: SiUnrealengine as unknown as LucideIcon,
  unity: SiUnity as unknown as LucideIcon,
  godot: SiGodotengine as unknown as LucideIcon,
  svg: SiSvg as unknown as LucideIcon,
  png: Image,
  jpg: Image,
  jpeg: Image,
  gif: Image,
  webp: Image,
  ico: Image,
  pdf: FileText,
  doc: FileText,
  docx: FileText,
  xls: Database,
  xlsx: Database,
  zip: Package,
  tar: Package,
  gz: Package,
  rar: Package,
  default: FileText,
}

const fileIconColors: Record<string, string> = {
  html: 'text-orange-500',
  htm: 'text-orange-500',
  css: 'text-blue-500',
  scss: 'text-pink-500',
  less: 'text-indigo-500',
  js: 'text-yellow-500',
  jsx: 'text-cyan-400',
  ts: 'text-blue-600',
  tsx: 'text-blue-500',
  json: 'text-emerald-500',
  md: 'text-slate-500',
  markdown: 'text-slate-500',
  txt: 'text-gray-500',
  py: 'text-sky-500',
  rs: 'text-orange-600',
  go: 'text-cyan-500',
  java: 'text-red-500',
  cpp: 'text-blue-700',
  c: 'text-blue-600',
  h: 'text-violet-500',
  hpp: 'text-violet-600',
  rb: 'text-red-600',
  swift: 'text-orange-500',
  kt: 'text-purple-500',
  kts: 'text-purple-500',
  php: 'text-indigo-500',
  hs: 'text-purple-600',
  ex: 'text-violet-500',
  exs: 'text-violet-500',
  scala: 'text-red-500',
  sql: 'text-amber-600',
  sh: 'text-green-600',
  bash: 'text-green-600',
  zsh: 'text-green-500',
  yaml: 'text-red-400',
  yml: 'text-red-400',
  xml: 'text-orange-400',
  dockerfile: 'text-blue-500',
  dockerignore: 'text-blue-500',
  gitignore: 'text-orange-500',
  node: 'text-green-500',
  package: 'text-red-500',
  lock: 'text-red-500',
  webpack: 'text-blue-500',
  vite: 'text-purple-500',
  babel: 'text-yellow-500',
  eslint: 'text-purple-500',
  prettier: 'text-pink-500',
  jest: 'text-red-500',
  mocha: 'text-red-500',
  cypress: 'text-green-500',
  vue: 'text-green-500',
  svelte: 'text-orange-500',
  angular: 'text-red-500',
  express: 'text-gray-500',
  nest: 'text-red-500',
  fastify: 'text-green-500',
  mongodb: 'text-green-500',
  postgresql: 'text-blue-500',
  mysql: 'text-blue-600',
  sqlite: 'text-blue-500',
  redis: 'text-red-500',
  nginx: 'text-green-500',
  apache: 'text-red-500',
  linux: 'text-yellow-500',
  ubuntu: 'text-orange-500',
  apple: 'text-gray-500',
  windows: 'text-blue-500',
  vscode: 'text-blue-500',
  sublime: 'text-orange-500',
  vim: 'text-green-500',
  neovim: 'text-green-500',
  obsidian: 'text-purple-500',
  notion: 'text-gray-500',
  figma: 'text-pink-500',
  photoshop: 'text-blue-600',
  illustrator: 'text-orange-500',
  premiere: 'text-purple-500',
  blender: 'text-orange-500',
  unreal: 'text-blue-500',
  unity: 'text-gray-500',
  godot: 'text-blue-500',
  svg: 'text-amber-500',
  png: 'text-pink-500',
  jpg: 'text-pink-500',
  jpeg: 'text-pink-500',
  gif: 'text-purple-500',
  webp: 'text-indigo-500',
  ico: 'text-blue-400',
  pdf: 'text-red-500',
  doc: 'text-blue-600',
  docx: 'text-blue-600',
  xls: 'text-green-600',
  xlsx: 'text-green-600',
  zip: 'text-amber-600',
  tar: 'text-amber-600',
  gz: 'text-amber-500',
  rar: 'text-purple-600',
  default: 'text-slate-500',
}

export const materialIconTheme: IconThemeDefinition = {
  id: 'material-icon-theme',
  name: 'Material Icon Theme',
  description: 'VS Code popular icon theme with Material Design style',
  fileIconMap,
  fileIconColors,
  folderIcon: MdFolder as unknown as LucideIcon,
  folderOpenIcon: MdFolderOpen as unknown as LucideIcon,
  defaultIcon: FileText,
  defaultColor: 'text-slate-500',
  folderColor: 'text-amber-500',
}
