import {
  FileText,
  type LucideIcon,
} from 'lucide-react'
import {
  VscFolder,
  VscFolderOpened,
  VscFile,
  VscFileCode,
  VscFileMedia,
  VscFilePdf,
  VscFileZip,
  VscTerminal,
  VscJson,
  VscCode,
  VscMarkdown,
  VscDatabase,
  VscSettingsGear,
  VscPackage,
  VscLock,
  VscBeaker,
  VscServerProcess,
  VscSymbolColor,
  VscPaintcan,
  VscPlay,
  VscDebugAlt,
  VscSourceControl,
} from 'react-icons/vsc'
import type { IconThemeDefinition } from './types'

const fileIconMap: Record<string, LucideIcon> = {
  html: VscCode as unknown as LucideIcon,
  htm: VscCode as unknown as LucideIcon,
  css: VscSymbolColor as unknown as LucideIcon,
  scss: VscSymbolColor as unknown as LucideIcon,
  less: VscSymbolColor as unknown as LucideIcon,
  js: VscCode as unknown as LucideIcon,
  jsx: VscCode as unknown as LucideIcon,
  ts: VscCode as unknown as LucideIcon,
  tsx: VscCode as unknown as LucideIcon,
  json: VscJson as unknown as LucideIcon,
  md: VscMarkdown as unknown as LucideIcon,
  markdown: VscMarkdown as unknown as LucideIcon,
  txt: VscFile as unknown as LucideIcon,
  py: VscFileCode as unknown as LucideIcon,
  rs: VscFileCode as unknown as LucideIcon,
  go: VscFileCode as unknown as LucideIcon,
  java: VscFileCode as unknown as LucideIcon,
  cpp: VscFileCode as unknown as LucideIcon,
  c: VscFileCode as unknown as LucideIcon,
  h: VscFileCode as unknown as LucideIcon,
  hpp: VscFileCode as unknown as LucideIcon,
  rb: VscFileCode as unknown as LucideIcon,
  swift: VscFileCode as unknown as LucideIcon,
  kt: VscFileCode as unknown as LucideIcon,
  kts: VscFileCode as unknown as LucideIcon,
  php: VscFileCode as unknown as LucideIcon,
  hs: VscFileCode as unknown as LucideIcon,
  ex: VscFileCode as unknown as LucideIcon,
  exs: VscFileCode as unknown as LucideIcon,
  scala: VscFileCode as unknown as LucideIcon,
  sql: VscDatabase as unknown as LucideIcon,
  sh: VscTerminal as unknown as LucideIcon,
  bash: VscTerminal as unknown as LucideIcon,
  zsh: VscTerminal as unknown as LucideIcon,
  yaml: VscSettingsGear as unknown as LucideIcon,
  yml: VscSettingsGear as unknown as LucideIcon,
  xml: VscCode as unknown as LucideIcon,
  dockerfile: VscServerProcess as unknown as LucideIcon,
  dockerignore: VscServerProcess as unknown as LucideIcon,
  gitignore: VscSourceControl as unknown as LucideIcon,
  node: VscServerProcess as unknown as LucideIcon,
  package: VscPackage as unknown as LucideIcon,
  lock: VscLock as unknown as LucideIcon,
  webpack: VscSettingsGear as unknown as LucideIcon,
  vite: VscSettingsGear as unknown as LucideIcon,
  babel: VscSettingsGear as unknown as LucideIcon,
  eslint: VscSettingsGear as unknown as LucideIcon,
  prettier: VscSettingsGear as unknown as LucideIcon,
  jest: VscBeaker as unknown as LucideIcon,
  mocha: VscBeaker as unknown as LucideIcon,
  cypress: VscBeaker as unknown as LucideIcon,
  vue: VscCode as unknown as LucideIcon,
  svelte: VscCode as unknown as LucideIcon,
  angular: VscCode as unknown as LucideIcon,
  express: VscServerProcess as unknown as LucideIcon,
  nest: VscServerProcess as unknown as LucideIcon,
  fastify: VscServerProcess as unknown as LucideIcon,
  mongodb: VscDatabase as unknown as LucideIcon,
  postgresql: VscDatabase as unknown as LucideIcon,
  mysql: VscDatabase as unknown as LucideIcon,
  sqlite: VscDatabase as unknown as LucideIcon,
  redis: VscDatabase as unknown as LucideIcon,
  nginx: VscServerProcess as unknown as LucideIcon,
  apache: VscServerProcess as unknown as LucideIcon,
  linux: VscTerminal as unknown as LucideIcon,
  ubuntu: VscTerminal as unknown as LucideIcon,
  apple: VscTerminal as unknown as LucideIcon,
  windows: VscTerminal as unknown as LucideIcon,
  vscode: VscCode as unknown as LucideIcon,
  sublime: VscFile as unknown as LucideIcon,
  vim: VscTerminal as unknown as LucideIcon,
  neovim: VscTerminal as unknown as LucideIcon,
  obsidian: VscMarkdown as unknown as LucideIcon,
  notion: VscFile as unknown as LucideIcon,
  figma: VscSymbolColor as unknown as LucideIcon,
  photoshop: VscPaintcan as unknown as LucideIcon,
  illustrator: VscPaintcan as unknown as LucideIcon,
  premiere: VscPlay as unknown as LucideIcon,
  blender: VscSymbolColor as unknown as LucideIcon,
  unreal: VscDebugAlt as unknown as LucideIcon,
  unity: VscDebugAlt as unknown as LucideIcon,
  godot: VscDebugAlt as unknown as LucideIcon,
  svg: VscSymbolColor as unknown as LucideIcon,
  png: VscFileMedia as unknown as LucideIcon,
  jpg: VscFileMedia as unknown as LucideIcon,
  jpeg: VscFileMedia as unknown as LucideIcon,
  gif: VscFileMedia as unknown as LucideIcon,
  webp: VscFileMedia as unknown as LucideIcon,
  ico: VscFileMedia as unknown as LucideIcon,
  pdf: VscFilePdf as unknown as LucideIcon,
  doc: VscFile as unknown as LucideIcon,
  docx: VscFile as unknown as LucideIcon,
  xls: VscFile as unknown as LucideIcon,
  xlsx: VscFile as unknown as LucideIcon,
  zip: VscFileZip as unknown as LucideIcon,
  tar: VscFileZip as unknown as LucideIcon,
  gz: VscFileZip as unknown as LucideIcon,
  rar: VscFileZip as unknown as LucideIcon,
  default: VscFile as unknown as LucideIcon,
}

const fileIconColors: Record<string, string> = {
  html: 'text-orange-400',
  htm: 'text-orange-400',
  css: 'text-blue-400',
  scss: 'text-pink-400',
  less: 'text-indigo-400',
  js: 'text-yellow-400',
  jsx: 'text-cyan-400',
  ts: 'text-blue-500',
  tsx: 'text-blue-400',
  json: 'text-emerald-400',
  md: 'text-slate-400',
  markdown: 'text-slate-400',
  txt: 'text-gray-400',
  py: 'text-sky-400',
  rs: 'text-orange-500',
  go: 'text-cyan-400',
  java: 'text-red-400',
  cpp: 'text-blue-600',
  c: 'text-blue-500',
  h: 'text-violet-400',
  hpp: 'text-violet-500',
  rb: 'text-red-500',
  swift: 'text-orange-400',
  kt: 'text-purple-400',
  kts: 'text-purple-400',
  php: 'text-indigo-400',
  hs: 'text-purple-500',
  ex: 'text-violet-400',
  exs: 'text-violet-400',
  scala: 'text-red-400',
  sql: 'text-amber-500',
  sh: 'text-green-500',
  bash: 'text-green-500',
  zsh: 'text-green-400',
  yaml: 'text-red-300',
  yml: 'text-red-300',
  xml: 'text-orange-300',
  dockerfile: 'text-blue-400',
  dockerignore: 'text-blue-400',
  gitignore: 'text-orange-400',
  node: 'text-green-400',
  package: 'text-red-400',
  lock: 'text-red-400',
  webpack: 'text-blue-400',
  vite: 'text-purple-400',
  babel: 'text-yellow-400',
  eslint: 'text-purple-400',
  prettier: 'text-pink-400',
  jest: 'text-red-400',
  mocha: 'text-red-400',
  cypress: 'text-green-400',
  vue: 'text-green-400',
  svelte: 'text-orange-400',
  angular: 'text-red-400',
  express: 'text-gray-400',
  nest: 'text-red-400',
  fastify: 'text-green-400',
  mongodb: 'text-green-400',
  postgresql: 'text-blue-400',
  mysql: 'text-blue-500',
  sqlite: 'text-blue-400',
  redis: 'text-red-400',
  nginx: 'text-green-400',
  apache: 'text-red-400',
  linux: 'text-yellow-400',
  ubuntu: 'text-orange-400',
  apple: 'text-gray-400',
  windows: 'text-blue-400',
  vscode: 'text-blue-400',
  sublime: 'text-orange-400',
  vim: 'text-green-400',
  neovim: 'text-green-400',
  obsidian: 'text-purple-400',
  notion: 'text-gray-400',
  figma: 'text-pink-400',
  photoshop: 'text-blue-500',
  illustrator: 'text-orange-400',
  premiere: 'text-purple-400',
  blender: 'text-orange-400',
  unreal: 'text-blue-400',
  unity: 'text-gray-400',
  godot: 'text-blue-400',
  svg: 'text-amber-400',
  png: 'text-pink-400',
  jpg: 'text-pink-400',
  jpeg: 'text-pink-400',
  gif: 'text-purple-400',
  webp: 'text-indigo-400',
  ico: 'text-blue-300',
  pdf: 'text-red-400',
  doc: 'text-blue-500',
  docx: 'text-blue-500',
  xls: 'text-green-500',
  xlsx: 'text-green-500',
  zip: 'text-amber-500',
  tar: 'text-amber-500',
  gz: 'text-amber-400',
  rar: 'text-purple-500',
  default: 'text-slate-400',
}

export const setiTheme: IconThemeDefinition = {
  id: 'seti',
  name: 'Seti',
  description: 'Clean monochrome file icons',
  fileIconMap,
  fileIconColors,
  folderIcon: VscFolder as unknown as LucideIcon,
  folderOpenIcon: VscFolderOpened as unknown as LucideIcon,
  defaultIcon: VscFile as unknown as LucideIcon,
  defaultColor: 'text-slate-400',
  folderColor: 'text-yellow-400',
}
