import {
  FileText,
  Terminal,
  Image,
  Database,
  Package,
  Pencil,
  Braces,
  Code,
  FileCode,
  FileJson,
  FileArchive,
  FileAudio,
  FileVideo,
  Folder,
  FolderOpen,
  type LucideIcon,
} from 'lucide-react'
import type { IconThemeDefinition } from './types'

const fileIconMap: Record<string, LucideIcon> = {
  html: FileCode,
  htm: FileCode,
  css: FileCode,
  scss: FileCode,
  less: FileCode,
  js: Code,
  jsx: Code,
  ts: Code,
  tsx: Code,
  json: FileJson,
  md: FileText,
  markdown: FileText,
  txt: FileText,
  py: Code,
  rs: Code,
  go: Code,
  java: Code,
  cpp: Code,
  c: Code,
  h: Code,
  hpp: Code,
  rb: Code,
  swift: Code,
  kt: Code,
  kts: Code,
  php: Code,
  hs: Code,
  ex: Code,
  exs: Code,
  scala: Code,
  sql: Database,
  sh: Terminal,
  bash: Terminal,
  zsh: Terminal,
  yaml: FileCode,
  yml: FileCode,
  xml: FileCode,
  dockerfile: Terminal,
  dockerignore: Terminal,
  gitignore: FileText,
  node: Code,
  package: Package,
  lock: Package,
  webpack: Package,
  vite: Package,
  babel: Code,
  eslint: Code,
  prettier: Code,
  jest: Code,
  mocha: Code,
  cypress: Code,
  vue: Code,
  svelte: Code,
  angular: Code,
  express: Code,
  nest: Code,
  fastify: Code,
  mongodb: Database,
  postgresql: Database,
  mysql: Database,
  sqlite: Database,
  redis: Database,
  nginx: Terminal,
  apache: Terminal,
  linux: Terminal,
  ubuntu: Terminal,
  apple: Terminal,
  windows: Terminal,
  vscode: Terminal,
  sublime: Terminal,
  vim: Terminal,
  neovim: Terminal,
  obsidian: FileText,
  notion: FileText,
  figma: Pencil,
  photoshop: Pencil,
  illustrator: Pencil,
  premiere: Pencil,
  blender: Image,
  unreal: Image,
  unity: Image,
  godot: Image,
  svg: Image,
  png: Image,
  jpg: Image,
  jpeg: Image,
  gif: Image,
  webp: Image,
  ico: Image,
  pdf: FileText,
  doc: FileText,
  docx: FileText,
  xls: Database,
  xlsx: Database,
  zip: FileArchive,
  tar: FileArchive,
  gz: FileArchive,
  rar: FileArchive,
  default: FileText,
}

const fileIconColors: Record<string, string> = {
  html: 'text-orange-400',
  htm: 'text-orange-400',
  css: 'text-blue-400',
  scss: 'text-pink-400',
  less: 'text-indigo-400',
  js: 'text-yellow-400',
  jsx: 'text-cyan-400',
  ts: 'text-blue-400',
  tsx: 'text-blue-400',
  json: 'text-emerald-400',
  md: 'text-slate-400',
  markdown: 'text-slate-400',
  txt: 'text-gray-400',
  py: 'text-sky-400',
  rs: 'text-orange-400',
  go: 'text-cyan-400',
  java: 'text-red-400',
  cpp: 'text-blue-400',
  c: 'text-blue-400',
  h: 'text-violet-400',
  hpp: 'text-violet-400',
  rb: 'text-red-400',
  swift: 'text-orange-400',
  kt: 'text-purple-400',
  kts: 'text-purple-400',
  php: 'text-indigo-400',
  hs: 'text-purple-400',
  ex: 'text-violet-400',
  exs: 'text-violet-400',
  scala: 'text-red-400',
  sql: 'text-amber-400',
  sh: 'text-green-400',
  bash: 'text-green-400',
  zsh: 'text-green-400',
  yaml: 'text-red-400',
  yml: 'text-red-400',
  xml: 'text-orange-400',
  dockerfile: 'text-blue-400',
  dockerignore: 'text-blue-400',
  gitignore: 'text-orange-400',
  node: 'text-green-400',
  package: 'text-red-400',
  lock: 'text-red-400',
  webpack: 'text-blue-400',
  vite: 'text-purple-400',
  babel: 'text-yellow-400',
  eslint: 'text-purple-400',
  prettier: 'text-pink-400',
  jest: 'text-red-400',
  mocha: 'text-red-400',
  cypress: 'text-green-400',
  vue: 'text-green-400',
  svelte: 'text-orange-400',
  angular: 'text-red-400',
  express: 'text-gray-400',
  nest: 'text-red-400',
  fastify: 'text-green-400',
  mongodb: 'text-green-400',
  postgresql: 'text-blue-400',
  mysql: 'text-blue-400',
  sqlite: 'text-blue-400',
  redis: 'text-red-400',
  nginx: 'text-green-400',
  apache: 'text-red-400',
  linux: 'text-yellow-400',
  ubuntu: 'text-orange-400',
  apple: 'text-gray-400',
  windows: 'text-blue-400',
  vscode: 'text-blue-400',
  sublime: 'text-orange-400',
  vim: 'text-green-400',
  neovim: 'text-green-400',
  obsidian: 'text-purple-400',
  notion: 'text-gray-400',
  figma: 'text-pink-400',
  photoshop: 'text-blue-400',
  illustrator: 'text-orange-400',
  premiere: 'text-purple-400',
  blender: 'text-orange-400',
  unreal: 'text-blue-400',
  unity: 'text-gray-400',
  godot: 'text-blue-400',
  svg: 'text-amber-400',
  png: 'text-pink-400',
  jpg: 'text-pink-400',
  jpeg: 'text-pink-400',
  gif: 'text-purple-400',
  webp: 'text-indigo-400',
  ico: 'text-blue-400',
  pdf: 'text-red-400',
  doc: 'text-blue-400',
  docx: 'text-blue-400',
  xls: 'text-green-400',
  xlsx: 'text-green-400',
  zip: 'text-amber-400',
  tar: 'text-amber-400',
  gz: 'text-amber-400',
  rar: 'text-purple-400',
  default: 'text-slate-400',
}

export const symbolsTheme: IconThemeDefinition = {
  id: 'symbols',
  name: 'Symbols',
  description: 'Minimalist symbol-based file icons',
  fileIconMap,
  fileIconColors,
  folderIcon: Folder as unknown as LucideIcon,
  folderOpenIcon: FolderOpen as unknown as LucideIcon,
  defaultIcon: FileText,
  defaultColor: 'text-slate-400',
  folderColor: 'text-amber-400',
}