import {
  FileText,
  type LucideIcon,
} from 'lucide-react'
import {
  VscFolder,
  VscFolderOpened,
  VscFile,
  VscFileCode,
  VscFileMedia,
  VscFilePdf,
  VscFileZip,
  VscTerminal,
  VscJson,
  VscCode,
  VscMarkdown,
  VscDatabase,
  VscPackage,
  VscLock,
  VscBeaker,
  VscServerProcess,
  VscSymbolColor,
  VscPaintcan,
  VscPlay,
  VscDebugAlt,
  VscSourceControl,
  VscGear,
  VscCircuitBoard,
} from 'react-icons/vsc'
import type { IconThemeDefinition } from './types'

const fileIconMap: Record<string, LucideIcon> = {
  html: VscCode as unknown as LucideIcon,
  htm: VscCode as unknown as LucideIcon,
  css: VscSymbolColor as unknown as LucideIcon,
  scss: VscSymbolColor as unknown as LucideIcon,
  less: VscSymbolColor as unknown as LucideIcon,
  js: VscCode as unknown as LucideIcon,
  jsx: VscCode as unknown as LucideIcon,
  ts: VscCode as unknown as LucideIcon,
  tsx: VscCode as unknown as LucideIcon,
  json: VscJson as unknown as LucideIcon,
  md: VscMarkdown as unknown as LucideIcon,
  markdown: VscMarkdown as unknown as LucideIcon,
  txt: VscFile as unknown as LucideIcon,
  py: VscFileCode as unknown as LucideIcon,
  rs: VscFileCode as unknown as LucideIcon,
  go: VscFileCode as unknown as LucideIcon,
  java: VscFileCode as unknown as LucideIcon,
  cpp: VscCircuitBoard as unknown as LucideIcon,
  c: VscCircuitBoard as unknown as LucideIcon,
  h: VscCircuitBoard as unknown as LucideIcon,
  hpp: VscCircuitBoard as unknown as LucideIcon,
  rb: VscFileCode as unknown as LucideIcon,
  swift: VscFileCode as unknown as LucideIcon,
  kt: VscFileCode as unknown as LucideIcon,
  kts: VscFileCode as unknown as LucideIcon,
  php: VscFileCode as unknown as LucideIcon,
  hs: VscFileCode as unknown as LucideIcon,
  ex: VscFileCode as unknown as LucideIcon,
  exs: VscFileCode as unknown as LucideIcon,
  scala: VscFileCode as unknown as LucideIcon,
  sql: VscDatabase as unknown as LucideIcon,
  sh: VscTerminal as unknown as LucideIcon,
  bash: VscTerminal as unknown as LucideIcon,
  zsh: VscTerminal as unknown as LucideIcon,
  yaml: VscGear as unknown as LucideIcon,
  yml: VscGear as unknown as LucideIcon,
  xml: VscCode as unknown as LucideIcon,
  dockerfile: VscServerProcess as unknown as LucideIcon,
  dockerignore: VscServerProcess as unknown as LucideIcon,
  gitignore: VscSourceControl as unknown as LucideIcon,
  node: VscServerProcess as unknown as LucideIcon,
  package: VscPackage as unknown as LucideIcon,
  lock: VscLock as unknown as LucideIcon,
  webpack: VscGear as unknown as LucideIcon,
  vite: VscGear as unknown as LucideIcon,
  babel: VscGear as unknown as LucideIcon,
  eslint: VscGear as unknown as LucideIcon,
  prettier: VscGear as unknown as LucideIcon,
  jest: VscBeaker as unknown as LucideIcon,
  mocha: VscBeaker as unknown as LucideIcon,
  cypress: VscBeaker as unknown as LucideIcon,
  vue: VscCode as unknown as LucideIcon,
  svelte: VscCode as unknown as LucideIcon,
  angular: VscCode as unknown as LucideIcon,
  express: VscServerProcess as unknown as LucideIcon,
  nest: VscServerProcess as unknown as LucideIcon,
  fastify: VscServerProcess as unknown as LucideIcon,
  mongodb: VscDatabase as unknown as LucideIcon,
  postgresql: VscDatabase as unknown as LucideIcon,
  mysql: VscDatabase as unknown as LucideIcon,
  sqlite: VscDatabase as unknown as LucideIcon,
  redis: VscDatabase as unknown as LucideIcon,
  nginx: VscServerProcess as unknown as LucideIcon,
  apache: VscServerProcess as unknown as LucideIcon,
  linux: VscTerminal as unknown as LucideIcon,
  ubuntu: VscTerminal as unknown as LucideIcon,
  apple: VscTerminal as unknown as LucideIcon,
  windows: VscTerminal as unknown as LucideIcon,
  vscode: VscCode as unknown as LucideIcon,
  sublime: VscFile as unknown as LucideIcon,
  vim: VscTerminal as unknown as LucideIcon,
  neovim: VscTerminal as unknown as LucideIcon,
  obsidian: VscMarkdown as unknown as LucideIcon,
  notion: VscFile as unknown as LucideIcon,
  figma: VscSymbolColor as unknown as LucideIcon,
  photoshop: VscPaintcan as unknown as LucideIcon,
  illustrator: VscPaintcan as unknown as LucideIcon,
  premiere: VscPlay as unknown as LucideIcon,
  blender: VscSymbolColor as unknown as LucideIcon,
  unreal: VscDebugAlt as unknown as LucideIcon,
  unity: VscDebugAlt as unknown as LucideIcon,
  godot: VscDebugAlt as unknown as LucideIcon,
  svg: VscSymbolColor as unknown as LucideIcon,
  png: VscFileMedia as unknown as LucideIcon,
  jpg: VscFileMedia as unknown as LucideIcon,
  jpeg: VscFileMedia as unknown as LucideIcon,
  gif: VscFileMedia as unknown as LucideIcon,
  webp: VscFileMedia as unknown as LucideIcon,
  ico: VscFileMedia as unknown as LucideIcon,
  pdf: VscFilePdf as unknown as LucideIcon,
  doc: VscFile as unknown as LucideIcon,
  docx: VscFile as unknown as LucideIcon,
  xls: VscFile as unknown as LucideIcon,
  xlsx: VscFile as unknown as LucideIcon,
  zip: VscFileZip as unknown as LucideIcon,
  tar: VscFileZip as unknown as LucideIcon,
  gz: VscFileZip as unknown as LucideIcon,
  rar: VscFileZip as unknown as LucideIcon,
  default: VscFile as unknown as LucideIcon,
}

const fileIconColors: Record<string, string> = {
  html: 'text-orange-500',
  htm: 'text-orange-500',
  css: 'text-blue-500',
  scss: 'text-pink-500',
  less: 'text-indigo-500',
  js: 'text-yellow-500',
  jsx: 'text-cyan-500',
  ts: 'text-blue-600',
  tsx: 'text-blue-500',
  json: 'text-emerald-500',
  md: 'text-slate-500',
  markdown: 'text-slate-500',
  txt: 'text-gray-500',
  py: 'text-sky-500',
  rs: 'text-orange-600',
  go: 'text-cyan-500',
  java: 'text-red-500',
  cpp: 'text-blue-700',
  c: 'text-blue-600',
  h: 'text-violet-500',
  hpp: 'text-violet-600',
  rb: 'text-red-600',
  swift: 'text-orange-500',
  kt: 'text-purple-500',
  kts: 'text-purple-500',
  php: 'text-indigo-500',
  hs: 'text-purple-600',
  ex: 'text-violet-500',
  exs: 'text-violet-500',
  scala: 'text-red-500',
  sql: 'text-amber-600',
  sh: 'text-green-600',
  bash: 'text-green-600',
  zsh: 'text-green-500',
  yaml: 'text-red-400',
  yml: 'text-red-400',
  xml: 'text-orange-400',
  dockerfile: 'text-blue-500',
  dockerignore: 'text-blue-500',
  gitignore: 'text-orange-500',
  node: 'text-green-500',
  package: 'text-red-500',
  lock: 'text-red-500',
  webpack: 'text-blue-500',
  vite: 'text-purple-500',
  babel: 'text-yellow-500',
  eslint: 'text-purple-500',
  prettier: 'text-pink-500',
  jest: 'text-red-500',
  mocha: 'text-red-500',
  cypress: 'text-green-500',
  vue: 'text-green-500',
  svelte: 'text-orange-500',
  angular: 'text-red-500',
  express: 'text-gray-500',
  nest: 'text-red-500',
  fastify: 'text-green-500',
  mongodb: 'text-green-500',
  postgresql: 'text-blue-500',
  mysql: 'text-blue-600',
  sqlite: 'text-blue-500',
  redis: 'text-red-500',
  nginx: 'text-green-500',
  apache: 'text-red-500',
  linux: 'text-yellow-500',
  ubuntu: 'text-orange-500',
  apple: 'text-gray-500',
  windows: 'text-blue-500',
  vscode: 'text-blue-500',
  sublime: 'text-orange-500',
  vim: 'text-green-500',
  neovim: 'text-green-500',
  obsidian: 'text-purple-500',
  notion: 'text-gray-500',
  figma: 'text-pink-500',
  photoshop: 'text-blue-600',
  illustrator: 'text-orange-500',
  premiere: 'text-purple-500',
  blender: 'text-orange-500',
  unreal: 'text-blue-500',
  unity: 'text-gray-500',
  godot: 'text-blue-500',
  svg: 'text-amber-500',
  png: 'text-pink-500',
  jpg: 'text-pink-500',
  jpeg: 'text-pink-500',
  gif: 'text-purple-500',
  webp: 'text-indigo-500',
  ico: 'text-blue-400',
  pdf: 'text-red-500',
  doc: 'text-blue-600',
  docx: 'text-blue-600',
  xls: 'text-green-600',
  xlsx: 'text-green-600',
  zip: 'text-amber-600',
  tar: 'text-amber-600',
  gz: 'text-amber-500',
  rar: 'text-purple-600',
  default: 'text-slate-500',
}

export const vscodeIconsTheme: IconThemeDefinition = {
  id: 'vscode-icons',
  name: 'VS Code Icons',
  description: 'Popular VS Code Icons extension theme',
  fileIconMap,
  fileIconColors,
  folderIcon: VscFolder as unknown as LucideIcon,
  folderOpenIcon: VscFolderOpened as unknown as LucideIcon,
  defaultIcon: VscFile as unknown as LucideIcon,
  defaultColor: 'text-slate-500',
  folderColor: 'text-yellow-500',
}
